homeのdesiginを変更
ShotaTanemura/ft_transcendence pull request #149
Opened 2024-09-14 17:13 UTC by libknt

2024-09-14 19:21 UTC, subarunrun0812 requested changes
アスペクト比を変更しても、見た目がおかしくなってないので非常に良いと思います。

一点だけコメント書きました！

2024-09-14 19:21 UTC, subarunrun0812 commented on pong/pong/static/pong/components/Home.js
> -            <form class="signout-form">
他にsingnoutボタンが実装されるまでは、signoutボタン残してほしいです。

2024-09-15 01:13 UTC, massahito commented on pong/pong/static/pong/components/Home.js
> -            <form class="signout-form">
置く場所に困ったらsingnoutはサイドバーとかでも全然OKです。

2024-09-15 01:29 UTC, massahito commented on pong/pong/static/pong/styles/home.styles.css
> +  display: flex;
おそらく毎回のコンポーネントでdisplayの配置を決めるであろうから、
https://github.com/ShotaTanemura/ft_transcendence/blob/184d0695bf3c4e7dd2dcc12a1691b185172d4e46/pong/pong/static/pong/styles/global.styles.css#L11
のdisplay flexを消してほしいです。これがあるとヘッダーが他のページで正しく描画されないっぽいです。

2024-09-15 01:29 UTC, massahito commented on pong/pong/static/pong/components/Home.js
> -            <form class="signout-form">
サイドバーにおくなら[この辺のアイコン](https://icons.getbootstrap.com/icons/box-arrow-in-left/)使うと良さそう。大変であったら私がプルリク出します。

2024-09-15 01:31 UTC, libknt commented on pong/pong/static/pong/components/Home.js
> -            <form class="signout-form">
![Uploading image.png…]()

2024-09-15 01:32 UTC, libknt commented on pong/pong/static/pong/components/Home.js
> -            <form class="signout-form">
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/e88a6648-fca6-4b02-b1eb-f13d24b7904e">

2024-09-15 01:32 UTC, libknt commented on pong/pong/static/pong/components/Home.js
> -            <form class="signout-form">
ありがとう！
全く同じiconちょうど見つけていました笑

2024-09-15 01:34 UTC, libknt commented on pong/pong/static/pong/styles/home.styles.css
> +  display: flex;
そこは他のcomponentに影響出していないです〜
以下のところで何も指定していないから他のcssがない状態で見えているだけかな！
global.styles.css
```
html,
body {
  font-size: 1rem;
  font-family: Arial, sans-serif;
  overflow-x: hidden;
  width: 100vw;
  height: 100vh;
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  display: flex;
}
```

2024-09-15 01:36 UTC, libknt commented on pong/pong/static/pong/styles/home.styles.css
> +  display: flex;
ここにflexが入ってました．
削除したので他のpageも戻っています！

2024-09-15 01:37 UTC, libknt commented on pong/pong/static/pong/styles/home.styles.css
> +  display: flex;
https://github.com/ShotaTanemura/ft_transcendence/pull/149/commits/8d5a5d08e18d66b319f98156cf87f8df6b040120

2024-09-15 01:37 UTC, libknt commented on pong/pong/static/pong/components/Home.js
> -            <form class="signout-form">
https://github.com/ShotaTanemura/ft_transcendence/pull/149/commits/b8e02fcf5ac3568ab95ff45341b30e37cb575af8

2024-09-15 01:40 UTC, massahito approved these changes
LGTM!!
迅速な対応ありがとうございました!！

2024-09-15 01:40 UTC, massahito commented on pong/pong/static/pong/styles/home.styles.css
> +  display: flex;
ありがとう!

2024-09-15 01:40 UTC, massahito commented on pong/pong/static/pong/components/Home.js
> -            <form class="signout-form">
素晴らしいです...

2024-09-15 07:14 UTC, subarunrun0812 approved these changes
LGTM

2024-09-15 07:14 UTC, merged