feat: そのユーザーの試合の勝敗を表示
ShotaTanemura/ft_transcendence pull request #215
Opened 2024-10-19 11:00 UTC by subarunrun0812

#202 
プロフィールに試合の勝敗結果を表示。
`/gamestats`ページと比べてより勝敗がわかるようにした。

課題文: ` User profiles display stats, such as wins and losses.`

![image](https://github.com/user-attachments/assets/705ca114-97fd-490a-a11e-15b472a5c84d)

2024-10-19 12:33 UTC, libknt requested changes
作成ありがとう！
ただ、今回の課題要件として、他人のユーザーProfileを確認する際にstatsを確認できるようにという用件が入っているため、そちらも作成お願いします！

2024-10-20 07:42 UTC, subarunrun0812 commented
ありがとうございます👍🏻
課題文のここですね！
> The user should be able to access other players profiles through the chat in-
terface.

対応しました！
ご確認お願いします！🙇

![image](https://github.com/user-attachments/assets/74836fdc-172d-4ca6-acc4-6e8710ac86d5)

2024-10-20 07:46 UTC, subarunrun0812 reviewed
他のUserのProfileを閲覧した際に、そのUserのゲーム結果が見れるようにしました！

2024-10-20 08:57 UTC, soooku reviewed
確認できました！！
リアクションゲームマージされたら勝敗結果いれてほしいです！！

2024-10-20 11:13 UTC, subarunrun0812 commented
リロードしないと全てのゲームの戦績が表示されないかも

2024-10-20 11:39 UTC, subarunrun0812 commented
scrollできな問題は、`overflow: hidden`が設定されていたのが原因でした。以下のコミットで修正しました
ebb7860fbfa0b35deab6811309b09f3772a2301b

2024-10-20 12:25 UTC, soooku approved these changes

2024-10-20 12:27 UTC, libknt approved these changes
LGTM!

2024-10-20 12:28 UTC, merged